version: '3'

services:
  web:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./app:/var/www/html:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - minecraft_auth
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    environment:
      - DOMAIN=${DOMAIN:-localhost}

  php:
    image: php:8.1-fpm
    volumes:
      - ./app:/var/www/html:ro
      - ./app/access_log:/var/www/html/access_log:rw
      - ./app/users.json:/var/www/html/users.json:ro
    environment:
      - MINECRAFT_PORT=${MINECRAFT_PORT:-25565}
      - SERVER_ADDRESS=${SERVER_ADDRESS:-your-server-address}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - minecraft_auth
    security_opt:
      - no-new-privileges:true
    user: www-data

  iptables_manager:
    build: ./iptables_manager
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL
    environment:
      - MINECRAFT_PORT=${MINECRAFT_PORT:-25565}
    volumes:
      - ./app/access_log:/app/access_log:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "iptables", "-L", "-n"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    network_mode: "host"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

volumes:
  caddy_data:
  caddy_config:

networks:
  minecraft_auth:
    driver: bridge