version: '3'

services:
  web:
    image: caddy:2
    ports:
      - "${WEB_HTTP_PORT:-80}:80"
      - "${WEB_HTTPS_PORT:-443}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./web:/var/www/html:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - portkey_auth
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - WEB_HTTP_PORT=${WEB_HTTP_PORT:-80}
      - WEB_HTTPS_PORT=${WEB_HTTPS_PORT:-443}

  php:
    image: php:8.1-fpm
    volumes:
      - ./web:/var/www/html:ro
      - ./web/access_log:/var/www/html/access_log:rw
      - ./web/passwd:/var/www/html/passwd:ro
    environment:
      - PORTS=${PORTS}
      - SERVER_ADDRESS=${SERVER_ADDRESS:-your-server-address}
      - WEB_HTTP_PORT=${WEB_HTTP_PORT:-80}
      - WEB_HTTPS_PORT=${WEB_HTTPS_PORT:-443}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - portkey_auth
    security_opt:
      - no-new-privileges:true
    user: www-data

  iptables_manager:
    build: ./iptables_manager
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL
    environment:
      - PORTS=${PORTS}
      - CHAIN_NAME=${CHAIN_NAME:-PORTKEY_AUTH}
    volumes:
      - ./web/access_log:/app/access_log:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "iptables", "-L", "-n"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    network_mode: "host"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

volumes:
  caddy_data:
  caddy_config:

networks:
  portkey_auth:
    driver: bridge